var l,p="undefined"==typeof browser,r=0<navigator.userAgent.indexOf("Edge/"),t=0<navigator.userAgent.indexOf("Firefox/"),u=0<navigator.userAgent.indexOf("OPR/");p&&(browser=chrome);
var w,x,y,aa,ba=t?69:r?77:66,ca=t?220:150,z=["127.0.0.1:1001","0.1.0.1:1001"],da=["main_frame","sub_frame"],C="main_frame sub_frame image object xmlhttprequest other".split(" "),E=["image","object","xmlhttprequest","other"],ea="origin referer dnt cookie user-agent accept-encoding".split(" "),fa=[301,302,303,307],ga=["*://*/*","ftp://*/*","file:///*"],G=["http://*/*","https://*/*"],ha=/\.([^.\\/]*?)(?:\.[0-9.]+)?$/,ia=browser.runtime.getURL("captured.html"),ja=browser.runtime.getURL("").slice(0,-1),
ka=browser.extension.getBackgroundPage().location.href,la=/(?:chrome|about|chrome-extension|ms-browser-extension|moz-extension):/,ma=["*://*.internetdownloadmanager.com/autoreg.html?*","*://*.internetdownloadmanager.com/fillregform.html?*"],na=/^(?:http|https):\/\/(?:www\.youtube\.com\/(?:watch\?|embed\/)|www\.facebook\.com\/(?:.+\/(?:videos|posts|permalink)\/(?:\w+\.\d+\/)?\d+\b|video\/\w+\/async\b|video\/embed\b|watch\b)|player\.vimeo\.com\/video\/\d+)/i,oa=/^(?:[\w\-]+\.)*?(?:youtube\.com|googlevideo\.com|youtube\.googleapis\.com|docs\.google\.com)$/i,
pa=/^(?:[\w\-]+\.)*?(?:vimeo\.com|vimeocdn\.com)$/i,qa=/^(?:www\.facebook\.com|(?:[\w\-]+\.)*?fbcdn\.net)$/i,ra=/^\/video\/\w+\/async\/(\d+)\//,sa=/\/(?:.+\/(?:videos|posts|permalink)\/(?:\w+\.\d+\/)?|video\/embed\?.*?\bvideo_id=|watch\/?\?.*?\bv=)(\d+)\b/,ta={16:1,17:2,18:4,45:8,46:16},ua={http:1,https:129,ftp:2,ftps:130,rtmp:3,rtmpt:3,rtmpe:3,mms:4,idmreg:159},va={"text/html":"HTML|HTM","text/css":"CSS","text/javascript":"JS|JSON","text/mspg-legacyinfo":"MSI|MSP","text/plain":"TXT|SRT","text/srt":"SRT",
"text/vtt":"VTT|SRT","text/xml":"XML|F4M|TTML","text/x-javascript":"JS|JSON","text/x-json":"JSON","application/f4m+xml":"F4M","application/gzip":"GZ","application/javascript":"JS","application/json":"JSON","application/msword":"DOC|DOCX|DOT|DOTX","application/pdf":"PDF","application/ttaf+xml":"DFXP","application/vnd.apple.mpegurl":"M3U8","application/zip":"ZIP","application/x-7z-compressed":"7Z","application/x-aim":"PLJ","application/x-compress":"Z","application/x-compress-7z":"7Z","application/x-compressed":"ARJ",
"application/x-dosexec":"EXE","application/x-gtar":"TAR","application/x-gzip":"GZ","application/x-gzip-compressed":"GZ","application/x-javascript":"JS","application/x-mpegurl":"M3U8","application/x-msdos-program":"EXE|DLL","application/x-msi":"MSI","application/x-msp":"MSP","application/x-ole-storage":"MSI|MSP","application/x-rar":"RAR","application/x-rar-compressed":"RAR","application/x-sdlc":"EXE|SDLC","application/x-shockwave-flash":"SWF","application/x-silverlight-app":"XAP","application/x-subrip":"SRT",
"application/x-tar":"TAR","application/x-zip":"ZIP","application/x-zip-compressed":"ZIP","video/3gpp":"3GP|3GPP","video/3gpp2":"3GP|3GPP","video/avi":"AVI","video/f4f":"F4F","video/f4m":"F4M","video/flv":"FLV","video/mp2t":"TS|M3U8","video/mp4":"MP4|M4V","video/mpeg":"MPG|MPEG","video/mpegurl":"M3U|M3U8","video/mpg4":"MP4|M4V","video/msvideo":"AVI","video/quicktime":"MOV|QT","video/webm":"WEBM","video/x-flash-video":"FLV","video/x-flv":"FLV","video/x-mp4":"MP4|M4V","video/x-mpegurl":"M3U|M3U8","video/x-mpg4":"MP4|M4V",
"video/x-ms-asf":"ASF","video/x-ms-wmv":"WMV","video/x-msvideo":"AVI","audio/3gpp":"3GP|3GPP","audio/3gpp2":"3GP|3GPP","audio/mp3":"MP3","audio/mp4":"M4A|MP4","audio/mp4a-latm":"M4A|MP4","audio/mpeg":"MP3","audio/mpeg4-generic":"M4A|MP4","audio/mpegurl":"M3U|M3U8","audio/webm":"WEBM","audio/wav":"WAV","audio/x-mpeg":"MP3","audio/x-mpegurl":"M3U|M3U8","audio/x-ms-wma":"WMA","audio/x-wav":"WAV","ilm/tm":"MP3","image/gif":"GIF|GFA","image/icon":"ICO|CUR","image/jpg":"JPG|JPEG","image/jpeg":"JPG|JPEG",
"image/png":"PNG|APNG","image/tiff":"TIF|TIFF","image/vnd.microsoft.icon":"ICO|CUR","image/webp":"WEBP","image/x-icon":"ICO|CUR","flv-application/octet-stream":"FLV"};function wa(){this.b=this.constructor.prototype.c++}wa.prototype.c=1;function xa(a,b,c,d){this.id=a;this.port=b;c&&(this.b=c.toLowerCase());d&&(this.url=d)}xa.prototype.a=0;function ya(a,b,c){this.id=[a,b].toString();this.b=0>c?null:[a,c].toString()}
function H(a,b,c,d,e,f){if(a){var h=["MSG#",a,"#",b,"#",c,"#",d];this.h=a;this.g=b;this.j=c;this.i=d;this.a=e||[];this.c=h;if(e)for(a=0;a<e.length;a++)h.push(":",e[a]||0);if(f)for(var g in f)if(e=f[g],null!=e)if(h.push(",",g,"="),"string"==typeof e){b=a=e.length;for(c=0;c<b;)d=e.charCodeAt(c++),128<=d&&(2048<=d?(a+=2,d-55296&56320||c++):a++);h.push(a,":",e)}else e instanceof Blob?h.push(e.size,":",e):h.push(e)}else this.f=new FileReader}
function za(a){a.N||(a.c.push(";"),a.N=!0);return a.c.join("")}function Aa(a){a.N||(a.c.push(";"),a.N=!0);return new Blob(a.c)}function Ba(a,b,c){a.N?a.w(a):(b.a=c||0,b.b=0,a.f.onload=a.La.bind(a,b),I(a,b,0,50))}l=H.prototype;
l.La=function(a){for(var b=this.f.result;;)switch(a.b){case 0:var c=b.split(",",2),d=c.shift().split(":",2),e=d.shift();if(!d.length){if(!c.length)return this.w(this);a.b=1}var f=e.length+1,d=e.split("#",6);if(5!=d.length||"MSG"!=d[0])return this.w(this);this.h=parseInt(d[1]);this.g=parseInt(d[2]);this.j=parseInt(d[3]);this.i=parseInt(d[4]);b=b.slice(f);a.a+=f;a.b++;break;case 1:d=b.split(",",2);e=d.shift();if(!d.length){d=b.split(";",2);if(2>d.length)return I(this,a,b.length,100);a.b=4}f=e.length+
1;this.a=d=e.split(":");for(e=0;e<d.length;e++)c=d[e],d[e]=c.includes(".")?parseFloat(c):parseInt(c);b=b.slice(f);a.a+=f;a.b++;break;case 2:c=b.split(",",2);2>c.length&&(c=b.split(";",2));var d=c.shift().split(":",2),h=d.shift(),f=h.length,e=!1;if(d.length)f++;else{if(!c.length)return I(this,a,b.length,25);e=!0}d=h.split("=",3);if(2!=d.length)return this.w(this);c=parseInt(d[0]);d=parseInt(d[1]);a.a+=f;a.b++;if(e){this[c]=d;b=b.slice(f);a.b++;break}a.f=c;a.c=d;b=a.c;f=a.a;a=a.slice(f,f+b);a.size==
b?this.f.readAsText(a):this.w(this);return;case 3:return this[a.f]=b,a.a+=a.c,a.b++,I(this,a,0,21);case 4:switch(b[0]){case ",":a.b=2;b=b.slice(1);break;case ";":a.b++;break;default:return this.w(this)}a.a++;break;case 5:this.N=!0;this.T(this);a.size>a.a&&(b=new H,b.T=this.T,b.w=this.w,Ba(b,a,a.a));return}};function I(a,b,c,d){var e=b.a;c=e+c;b.size>c?a.f.readAsBinaryString(b.slice(e,c+d)):a.w(a)}l.l=null;l.T=null;l.w=null;l.N=!1;
function J(){if(w){var a=this.constructor.prototype,b;for(b in a)b.startsWith("_")||"constructor"==b||(this[b]=a[b].bind(this));this.ua=[];this.R=!1;this.S=this.ca=null;this.c={};this.u={};this.a={};this.i={};this.b={};this.j={};this.g={};this.f={};this.B={};this.aa="";this.ba=!0;this.Ia=this.va=this.Ha=1;this.A={};this.h=null;this.Z=1;this.m=!1;this.J=0;this.M=null;this.v=u;this.P=0;this.ta=null;this.$=this.O=!1;p&&browser.browserAction.disable();browser.windows.onCreated.addListener(this.Ba);browser.windows.onRemoved.addListener(this.Ca);
browser.windows.onFocusChanged.addListener(this.Ya);browser.tabs.onActivated.addListener(this.Sa);browser.tabs.onUpdated.addListener(this.Ua);browser.tabs.onAttached&&browser.tabs.onAttached.addListener(this.Ta);this.sa();this.ea();Ca(this,!0)}}
function Ca(a,b){var c=a.c,d=a.A={};browser.contextMenus.removeAll();for(var e=0;e<Da.length;e++){var f=Da[e];f[0]&&(t?b||c[f[1]]:1)&&(d[e]=browser.contextMenus.create({title:Ea(f[2]),contexts:f[3].split(","),onclick:f[4].bind(a),documentUrlPatterns:f[5]||ga,enabled:!0}))}}function Fa(a,b,c,d,e){a=a.g;return b in a?a[b]:a[b]=new xa(b,c,d,e)}function Ga(a,b){var c=a.f,d=b.requestId;c[d]=b;var e=b.id;e||(e=b.id=r?a.Ia++:d);e!=d&&(c[e]=b,c=a.i[[b.tabId,b.frameId]])&&(c.a=e)}
function Ha(a,b,c,d){var e=[b,c].toString();a=a.i;return e in a?a[e]:a[e]=new ya(b,c,d)}function Ia(a){var b=new wa;return a.j[b.b]=b}function L(a,b){var c=a.j[b];c&&delete a.j[b];return c}l=J.prototype;
l.ea=function(){var a=this.J%(z.length+1);if(a<z.length)this.ca=a=new WebSocket("ws://"+z[a]+"/?cid="+Math.random().toString().substr(2,9),"plugin.v3.internetdownloadmanager.com"),a.onopen=this.ia,a.onclose=this.F,a.onmessage=this.Ra,1==a.readyState?this.ia():3==a.readyState&&this.F();else{this.S=a=browser.runtime.connectNative("com.tonec.idm");try{a.postMessage("")}catch(b){a=null}a?(a.onDisconnect.addListener(this.F),a.onMessage.addListener(this.Na),this.ia()):this.F()}};
l.ia=function(){this.m=!0;this.va=1;var a=[4,10,this.v?6:7,0],b={};b[112]=y;b[113]=x;b[114]="Chrome_RenderWidgetHostHWND";if(587202560<=w){var c=browser.i18n.getUILanguage().replace("_","-");"sr"==c&&(c+="-Cyrl-CS");b[116]=c}M(this,2,1,0,a,b)};
l.F=function(){browser.runtime.lastError;this.ca=this.S=null;if(this.m){this.m=!1;this.B={};for(var a=this.ua,b=0;b<a.length;b++){var c=a[b],d=c.splice(0,2).pop();a.splice(b--,1);r&&c.splice(1);d.removeListener.apply(d,c)}this.R=!1;this.M=null;p&&browser.browserAction.disable()}a=++this.J;b=z.length+1;c=a/b;120>c&&(1==c&&this.ba&&this.da(),!a||a%b?this.ea():window.setTimeout(this.ea,5E3*c))};l.Ra=function(a){var b=new H;b.T=this.za;b.w=this.F;Ba(b,a.data)};
l.Na=function(a){var b=new H;b.T=this.za;b.w=this.F;Ba(b,new Blob([a]))};function M(a,b,c,d,e,f){if(a.m){var h=a.va++;b=new H(h,b,c,d,e,f);if(c=a.ca)c.send(Aa(b));else try{a.S.postMessage(za(b))}catch(g){a.F();return}d&1&&(a.B[h]=b)}}
function Ka(a,b){var c=a.f;if(b.a){var d=b.a[6],e=d&&c[d];if(e){var f=e.type;return!f||"image"==f||e.c?(b.l=e.port.id,b.m=d,!0):!1}}var h=a.a,g=a.g,k=b[6],m=b[17],n=b[50],q=b[7],B,D;for(d in c){var e=c[d],v=e.url;if(v){if(v==k||v==m)if(f=e.type,!f||"image"==f||e.c)return b.l=e.port.id,b.m=parseInt(d),!0;v==n&&(D=e.port.id)}}for(d in g)if(c=g[d],v=c.url){if(v==k||v==m||v==n)if(e=c.port,q&&(f=h[e.tabId])&&f.url!=q&&(e=null),e)return b.l=e.id,!0;v==q&&(B=c.port.id)}return null!=D?(b.l=D,!0):null!=B?
(b.l=B,!0):!1}l.xa=function(a,b,c,d){if(b)return d?(b=(c=d.shift())&&this.a[c.id])?a.l=b.id:null:null;if(null!=a.l)return a.l;if(a.a){var e=a.a[7];if(e&&this.u[e])return a.l=e}if(Ka(this,a))return a.l;d=this.u;var f=a[50],h=a[7];for(e in d){b=d[e];if(b.url==f){a.l=e;break}null==a.l&&b.url==h&&(a.l=e)}if(null!=a.l)return a.l;h&&browser.tabs.query({url:h},La(this,a,!0,c));return null};
l.ga=function(a,b,c,d,e,f){var h=a.tabId,g=a.frameId,k=a.windowId,m=a.b,n;if(void 0===b){if(f=new P(this,a,!0),null==k&&(a.a?(browser.tabs.get(h,Q(f,2)),browser.windows.getLastFocused(Q(f,3))):(k=this.a[h],a.windowId=k&&k.windowId)),null==g&&a.url?browser.webNavigation.getAllFrames({tabId:h},Q(f,5)):g&&null==m&&browser.webNavigation.getFrame({frameId:g,tabId:h},Q(f,4)),f.c())return}else if(b&&(c&&0<=c.index?a.windowId=c.windowId:d&&(a.windowId=d.id),e&&(n=e.parentFrameId),f))for(c=a.url,d=c.includes("#")&&
Ma(c),e=f.length-1;0<=e;e--)if(k=f[e],b=k.url,!k.Za&&k.frameId&&(b==c||d&&b==d)){g=a.frameId=k.frameId;n=k.parentFrameId;break}if(null==g)a.url||a.postMessage([11,h,null,!0,a.c]);else{f=[h,g].toString();0<=n&&(m=a.b=[h,n].toString());if(k=this.i[f])a.i=k.a,a.c=k.c,(b=k.G)&&a.url!=b&&(a.G=b),!m&&k.b&&(a.b=k.b);this.a[f]=a;a.postMessage([11,h,g,!a.url,a.c])}};
l.W=function(a,b,c,d,e,f,h,g){var k=Na(a,!0);if(!k)return 0;if(1==k){if(!h)return R(a,La(this,a,b,c,d,e,f,!0)),-1;"object"==typeof g&&(g=Oa(g))}h=[k];k={};k[6]=a;k[50]=b;k[7]=c;k[8]=d;k[100]=e;k[102]=f;k[51]=g;k[54]=navigator.userAgent;M(this,14,1,0,h,k);return 3};
l.Fa=function(a,b,c,d,e){if(!d){if(!a||!a.length)return;c||(c={});var f=new P(this,a,b,c,!0);c.pageUrl&&!c.Da&&R(c.pageUrl,Q(f,4));for(var h=0;h<a.length;h++)R(a[h][0],Q(f,5+h));if(f.c())return}e&&(c.Da=Oa(e));for(h=0;h<a.length;h++)a[h][5]=Oa(arguments[h+5]);var f=0,h=[a.length],g={8:4};g[54]=navigator.userAgent;g[7]=c.pageUrl;g[110]=c.H;g[111]=c.Da;1<a.length&&(M(this,15,1,f,h,g),f=16,g={});for(var h=[0],k;k=a.shift();)g[6]=k[0],g[100]=k[2],g[102]=k[3],g[50]=k[4],g[51]=k[5],M(this,14,1,f,h,g)};
function R(a,b){var c={url:a};aa&&(c.firstPartyDomain=null);browser.cookies.getAll(c,b)}function S(a,b,c,d){(b=b[c])?(b=d?b.replace(/\./g,"\\.").replace(/\?/g,".").replace(/\*/g,".*").replace(/~/g,"(?:.*\\.)?"):b.replace(/\?/g,".").replace(/\*/g,".*"),b="^(?:"+b.replace(/\|{2,}/g,"|")+")$"):b="(?!)";a.c[c]=new RegExp(b,"i")}
function Pa(a,b,c,d,e,f,h,g){if(!d||a.c[-8]){var k=a.a[b];if(k){var m=Ia(a),n=m.b;m.tabId=b;m.port=k;m.j=c;m.a=0;m.m=[];if(k=d&&!!e)m.B=!0,m.u=e,m.g=f,m.h=h,m.zoom=g,e.a||Qa(a,e);e="^(?:http|https|ftp|ftps|rtmp|rtmpt|rtmpe|mms)://";d&&(d=a.c[12])&&(d=d.replace(/\./g,"\\."),d=d.replace(/\*/g,".*"),d=d.replace(/\~/g,"(?:.*\\.)?"),e=e+"(?:[^\\/]*@)?(?:"+d+")(?::\\d+)?(?:\\W|$)");m.f=Ra(a,b,[12,n,c,k,e]);m.v=0;m.f||L(a,n)}}}
l.K=function(a,b,c){if(4294967295==a)this.h=null,c=!0;else{var d=this.g[a];if(d){c=d.a;if(!c)return;if(b)switch(c){case 3:return;case 2:break;default:d.a=3;window.setTimeout(this.K.bind(this,a,!1,!0),1E3);return}d.a=0;c=!0}}c&&M(this,8,1,32,[a])};function Sa(a,b){var c=a.b[b];if(c&&c.U){var d=c.border,e=c.scale;M(a,7,1,0,[b,Math.round((c.Y+d)*e),Math.round((c.qa+d)*e),Math.round((c.width-d-c.na)*e),Math.round((c.height-d)*e)])}}
function Ta(a,b,c,d){var e=a.g[b],f=256;2==e.a&&(d?(f|=128,e.a=1):f|=64);var h,g,k,m,n;c&&(h=c.left,g=c.top,k=c.right||h+1,m=c.bottom||g+1,n=c.zoom,c=e.port.f)&&(h+=c.left,g+=c.top,k=Math.min(k+c.left,c.right),m=Math.min(m+c.top,c.bottom));M(a,9,1,f,[b,h,g,k,m,n])}
l.X=function(a){var b=this.b,c=[];if(a)(a=b[a])&&(a.C||a.D||c.push(a.s));else for(var d in b)a=b[d],a.C||a.D||c.push(a.s);if(c.length){b=[15,null,null];a={};var e=this.g;for(d in e){var f=e[d];f.a&&0<=c.indexOf(f.port.tabId)&&(f.b?(f=f.port,f.a||Qa(this,f,null,a),b[2]=d,f.postMessage(b)):Ta(this,d,null,!0))}}};function Ua(a,b){var c=a.b[b];c&&!c.D&&T(a,c.s,void 0)}function T(a,b,c){var d=c?0:2;c=c?32:64;var e=a.g,f;for(f in e){var h=e[f];h.a&&h.port.tabId==b&&h.a!=d&&(h.a=d,M(a,8,1,c,[f]))}}
function U(a,b,c,d){var e=a.P,f=(e&b)!=((c?63:32)&b);a.P=c?e|=b:e&=~b;f&&(c=a.c[-1],b=a.c[-2],c=a.O=0!=c&&(e&c)==c,e=a.$=0!=b&&(e&b)==b,a.ta=(c||e)&&d||null)}l.ra=function(a,b,c,d){var e=this.b[a];if(e)if(d)e.D&&window.clearTimeout(e.D),e.D=window.setTimeout(this.ra.bind(this,a,b,c),d);else if(e.D=null,b&&(browser.windows.get(a,this.I),browser.tabs.query({windowId:a,active:!0},this.I)),c){if((a=this.b[a])&&!a.D){a=a.s;b=this.g;for(var f in b)c=b[f],c.a&&c.port.tabId==a&&1==c.a&&M(this,8,1,1152,[f])}}else this.X(a)};
l.I=function(a,b){a instanceof Array&&(a=a.shift());if(a){var c=a.windowId||a.id,d=this.b[c];if(d){if(a.windowId){if(d.ready&&la.test(a.url))return;d.s=a.id;a.width&&(d.pa=a.width);a.height&&(d.oa=a.height)}else{var e=b?d.scale=this.Z:d.scale,f="fullscreen"==a.state,h=!b&&f!=d.C;d.C=f;d.ya="maximized"==a.state;d.ha="minimized"==a.state;r?(d.width=Math.round(a.width/e),d.height=Math.round(a.height/e),d.left=Math.round(a.left/e),d.top=Math.round(a.top/e)):(d.width=a.width,d.height=a.height,d.left=a.left,
d.top=a.top);h&&(f?Ua(this,c):this.X(c))}h=d.pa;e=d.oa;if(h&&e){var g=d.width,f=d.height;if(!d.ready&&!d.ha){if(h>g||e>f)return browser.windows.get(c,this.I);d.ready=!0}h=g-h;g=h/2;0<=g&&20>=g?(d.border=g,d.Y=d.na=0):(g=d.border,t||u?d.Y=h-2*g:d.na=h-2*g);e=f-e-2*g;e<=ca&&(d.qa=e)}b||Sa(this,c);return d}}};
function Qa(a,b,c,d){a=a.a;c=[16,c];for(var e=[b],f;f=a[b.b];b=f){if(d)if(d[b.id])break;else d[b.id]=!0;e.push(f)}for(f=e.pop();b=e.pop();f=b)d=b.Ka,c[2]=d,c[3]=b.frameId,c[4]=d?null:b.url,c[5]=d?null:b.G,f.postMessage(c)}function Ra(a,b,c){a=a.a;b=[b,null].toString();var d=0,e;for(e in a)e.startsWith(b)&&(a[e].postMessage(c),d++);return d}
l.V=function(a){function b(a){a;browser.runtime.lastError}var c={file:"content.js",runAt:"document_start",allFrames:!0};620756992<=w&&(c.matchAboutBlank=!0);if(a instanceof Array)for(;a.length;)try{browser.tabs.executeScript(a.shift().id,c,b)}catch(d){}else try{browser.tabs.executeScript(a.id||a,c,b)}catch(d){}};function Va(a,b,c,d){var e=17,f=[b.id,b.U,b.width,b.height,b.left,b.top,b.scale],h={};b.ya&&(e|=256);b.ha&&(e|=512);null!=c&&(e|=c?2048:1024);d&&(h[117]=d);M(a,6,2,e,f,h)}
l.sa=function(a,b){if(b)for(;b.length;){var c=b.shift(),d=this.I(c,!0)||this.Ba(c);Va(this,d,c.focused,c.title)}else if(!a){c=this.sa.bind(this,!0);try{browser.windows.getAll({windowTypes:["normal","popup"]},c)}catch(e){browser.windows.getAll(c)}}};
l.fa=function(a,b){if(!this.m)return Wa(b.id,"cannot_contact_idm");var c=a.linkUrl,d=a.pageUrl,e=d;if(a.menuItemId==this.A[4])return browser.downloads.search({query:[c]},this.Ja.bind(this,c));if(a.menuItemId==this.A[1])c=a.frameUrl,c||(c=d,e=null);else if(!c){var c=a.srcUrl,f=this.a[[b.id,a.frameId].toString()];if(f){var h=Ia(this);h.tabId=b.id;h.port=f;h.url=c;h.A=e;h.pageUrl=d;h.i=4;return f.postMessage([18,h.b,c])}}c&&this.W(c,e,d,4)};
l.wa=function(a,b){if(!this.m)return Wa(b.id,"cannot_contact_idm");Pa(this,b.id,a.menuItemId==this.A[2])};l.Ja=function(a,b){for(var c,d,e;c=b.pop();)c.exists&&"complete"==c.state?d||e||(e=c.referrer):(d||(d=c.referrer),browser.downloads.erase({id:c.id}));this.W(a,d||e,null,4)};
l.Oa=function(a){var b=a.sender.tab;if(b&&!(0>b.id)){var c=a.id;null==c&&(c=a.id=a.portId_||this.Ha++);var d=b.id,e="top"==a.name;a.tabId=d;a.windowId=0>b.index?null:b.windowId;a.g=!0;a.h=!1;a.a=e;a.frameId=e?0:a.sender.frameId;a.j=0;a.url=a.sender.url||e&&b.url||null;a.G=null;this.u[c]=a;e&&(this.a[d]=a);a.onMessage.addListener(this.Pa.bind(this,a));a.onDisconnect.addListener(this.ja);this.ga(a)}};
l.ja=function(a,b){browser.runtime.lastError;if(a.g){b||(a.g=!1);var c=this.g,d=this.f,e=this.j,f,h,g;for(g in c)if(f=c[g],f.port===a)f.a&&this.K(g),delete c[g];for(g in d)(h=d[g],h.port!==a||h.g)||(delete d[g],r&&delete d[h.id]);for(g in e)e[g].port===a&&delete e[g];this.ta===a&&U(this,63,!1);if(!b){c=a.tabId;d=a.frameId;e=[c,d].toString();f=this.i;for(g in f)e==f[g].b&&delete f[g];a.a&&delete this.a[c];delete this.a[[c,d]];delete this.u[a.id]}}};
l.Pa=function(a,b){switch(b[0]){case 21:var c=b[1];c&&(a.url=c,null==a.frameId&&this.ga(a));break;case 22:var d=this.a,e=d[[a.tabId,b[2]]];e&&(e.Ka=b[3],c=e.f=b[4],d=d[e.b])&&(d=d.f)&&(c.left+=d.left,c.top+=d.top,c.right=Math.min(c.right+d.left,d.right),c.bottom=Math.min(c.bottom+d.top,d.bottom));break;case 23:var c=a.windowId,f=a.tabId,h=b[1],d=b[2],e=b[4],g=this.b[c];if(h){if(h=L(this,h)){var g=f==g.s&&!g.C,k=!d||!e;k&&(d=f);if(f=b[7])h[101]||h.L&&h.H&&h.L!=h.H||(h.L=f),h.H=f;var f=Fa(this,d,a,
k?null:b[5],k?null:b[6]),m=g&&!f.a;f.a=g?1:2;h instanceof H&&V(this,h,2,(g?128:64)|(k?512:0),c,d,h.L);k||(Ta(this,d,e),m&&window.setTimeout(this.X.bind(this,c),3E3))}}else b[3]?(this.K(d,!0),delete this.g[d]):e&&f==g.s&&!g.C&&Ta(this,d,e,!0);break;case 24:c=b[2];(d=this.j[b[1]])&&c&&(d[101]||d.L&&d.H&&d.L!=d.H||(d.L=c),d.H=c);break;case 25:Fa(this,b[1],a,b[2],b[3]);break;case 26:Pa(this,a.tabId,!0,!0,a,b[1],b[2],b[3]);break;case 27:if(c=this.j[b[1]]){d=c.m;if(e=b[4])if("string"==typeof e&&(e=JSON.parse(e)),
e instanceof Array){if(h=b[5])for(g=0;g<e.length;g++)e[g][4]=h;Array.prototype.push.apply(d,e)}b[3]&&(c.a+=b[3]);b[6]&&(c.pageUrl=b[6]);b[7]&&(c.H=b[7]);++c.v<c.f||(L(this,c.b),c.B?(d=c.port,(d=this.b[d.windowId])&&d.s==c.tabId&&c.a&&(c.frame=c.u.f,e=c.zoom,h=d.border,g=d.scale,M(this,10,1,0,[4294967295,d.id,Math.round(c.g*e+(d.Y+h)*g),Math.round(c.h*e+(d.qa+h)*g),0,c.a]),this.h=c.tabId,Ra(this,c.tabId,[13,!0]))):d.length?this.Fa(d,c.j,c):Wa(c.tabId,"cannot_find_links"))}break;case 28:this.K(4294967295);
break;case 29:Xa(this,a.windowId,a.tabId);break;case 30:Xa(this,a.windowId,a.tabId,b[1],b[2]);break;case 31:(c=ta[b[1]])&&U(this,c,b[2],a);break;case 32:0==b[1]&&U(this,32,b[2],a);break;case 33:U(this,63,!1);break;case 34:c=b[2];d=b[3];e=b[4];b[1]&&(h=a.i)&&(h=[h,d||0],g={},k=32,g[110]=c,g[115]=e,-2==d&&(k|=16),M(this,16,1,k,h,g));break;case 35:c=b[2];d=b[3];(e=L(this,b[1]))&&this.W(e.url,e.A,e.pageUrl,e.i,c,d);break;case 36:if(e=b[1],c=b[2],d=this.f[e])e=[e,0],h={},h[115]=c,M(this,16,1,48,e,h),d.m=
null,d.A&&W(this,d)}};
l.za=function(a){var b=a.g,c=a.j,d=a.i,e=a.a,f;if(1==b){var h=e[0];if(f=this.B[h])b=f.g,delete this.B[h]}switch(b){case 3:var g=e[0],d=this.J;0<=d&&(this.J=-1,d%=z.length+1,4<=g&&d<z.length&&(this.M="http://"+z[d]+"/status/204+IDM"));this.aa=a[13]||"m"+e[2];if(g=e[4])g/=96,p&&(g=620756992>w?1:620756992<=w&&621284967>w?g:637534208<=w&&638078312>w?g:1.24<g?g:1),this.Z=g,this.sa();this.ba&&this.da();break;case 4:g=this.c;g[-9]=0<(d&64);g[-8]=0<(d&32);g[-4]=0<(d&2);g[-11]=0<(d&256)||2>c;g[-12]=0<(d&512)||
2>c;g[-1]=e[0];g[-2]=e[1];g[12]=a[12];S(this,a,1);S(this,a,2);S(this,a,3);S(this,a,4);S(this,a,10);S(this,a,9,!0);S(this,a,11,!0);if(g=a[13])this.aa=g;Ca(this);this.R||(this.R=!0,p&&browser.browserAction.enable(),this.o(1,browser.runtime.onConnect,this.Oa),this.o(1,browser.webNavigation.onCommitted,this.Aa),this.o(1,browser.webNavigation.onHistoryStateUpdated,this.Ma),g=t?void 0:C,d=["requestBody","blocking"],e=["requestHeaders","blocking"],a=["requestHeaders"],c=["responseHeaders","blocking"],f=
["responseHeaders"],p&&1207959552<=w&&(e.push("extraHeaders"),1208887889<w&&1225679651>w&&a.push("extraHeaders")),this.v?(this.o(2,browser.webRequest.onBeforeRequest,this.ka,{urls:["*://*/*"],types:g},d),this.o(2,browser.webRequest.onBeforeSendHeaders,this.la,{urls:["*://*/*"],types:g},e),this.o(2,browser.webRequest.onHeadersReceived,this.ma,{urls:["*://*/*"],types:g},c)):(this.o(2,browser.webRequest.onBeforeRequest,this.ka,{urls:["http://*/*"],types:da}),this.o(2,browser.webRequest.onBeforeRequest,
this.ka,{urls:["https://*/*"],types:g},d),this.o(2,browser.webRequest.onBeforeSendHeaders,this.la,{urls:["http://*/*"],types:g},a),this.o(2,browser.webRequest.onBeforeSendHeaders,this.la,{urls:["https://*/*"],types:g},e),this.o(2,browser.webRequest.onHeadersReceived,this.ma,{urls:["http://*/*"],types:g},f),this.o(2,browser.webRequest.onHeadersReceived,this.ma,{urls:["https://*/*"],types:g},c)),this.o(3,browser.webRequest.onResponseStarted,this.Xa,{urls:["*://*/*"],types:g}),this.o(3,browser.webRequest.onErrorOccurred,
this.Wa,{urls:["*://*/*"],types:g}),this.o(3,browser.webRequest.onBeforeRequest,this.Va,{urls:ma,types:da},["blocking"]),browser.tabs.query({url:G[0]},this.V),browser.tabs.query({url:G[1]},this.V));break;case 5:g=e[0];(e=this.b[g])?(d=0!=(d&128),e.C!=d&&(e.C=d)&&Ua(this,g)):this.Ca(g);break;case 6:if(d&4)break;g=f.a[0];d=e[1];if(e=this.b[g])e.U=d,Sa(this,g);break;case 8:g=e[0];d&=32;if(4294967295==g)Ra(this,this.h,[13,!1]),this.h=null;else if(g=this.g[g])g.a=d?0:2;break;case 11:g=e[0];4294967295==
g&&(Pa(this,this.h,!0,!0),this.h=null);break;case 12:try{var k=a.a[5],m=a[4],g=4==k?2:3;if((1==k||2==k)&&Ka(this,a)){if(this.c[3].test(m))1==k?g=4:k=4;else if(this.c[-4]||this.c[4].test(m))g=4;a[8]|=256}if(4==k){switch(a.a[4]){case 1:a[7]||(a[7]=a[50]);break;case 3:a[7]||(a[7]=a[32]),a[50]||(a[50]=a[31])}this.Ea(a)}else V(this,a,g)}catch(n){V(this,a,0)}break;case 13:d=f.a[0];a=f.a[5];e=e[1];if(1==a||2==a)W(this,d,null,3==e);else if(5==a)if(e){if(a=this.f[d]){d=a.j;e=a.requestHeaders;"POST"==a.method&&
(g=Ya(a.f,Y(e,"Content-Type")));d.timeout=1E4;d.onreadystatechange=this.Qa.bind(this,d,a.id);d.open(g?"POST":"GET",a.url,!0);for(a=0;a<e.length;a++)c=e[a],f=c.name,0<=ea.indexOf(f.toLowerCase())&&(f="X-IDM-"+f),d.setRequestHeader(f,c.value);d.send(g)}}else Za(this,d);break;case 1:break;default:!f&&d&1&&M(this,1,1,0,[a.h,0,0,0])}};
l.Ea=function(a,b,c){try{if(null==a.l)if(!b){var d=new P(this,a,!0);this.xa(a,null,d)||browser.windows.getLastFocused(Q(d,2));if(d.c())return}else if(c){var e=this.b[c.id],f=this.a[e&&e.s];f&&(a.l=f.id)}f=this.u[a.l];if(!f)return V(this,a,0);var h;var g=a.b;g||(g=wa.prototype.c++,a.b=g,this.j[g]=a);h=g;if(!f.a){var k=this.a[f.tabId];k&&k.postMessage([14,h])}var m=[15,h,null,a[6],a[17],a[50],a[31]];f.a||Qa(this,f,h);f.postMessage(m)}catch(n){V(this,a,0)}};
function V(a,b,c,d,e,f,h){-1!=c&&(e=[b.h,c,e,f],f={},f[8]=b[8],h&&(f[110]=h),M(a,1,1,d|(0==c?4:2),e,f))}l.Aa=function(a,b){var c=a.tabId,d=a.frameId,e=a.url,f=this.a[[c,d]];f?b?e!=f.url&&(this.ja(f,!0),f.url=e,f.j++,f.postMessage([17,!1,f.c])):this.ja(f):0<d&&"about:blank"==e&&(Ha(this,c,d,a.parentFrameId),this.V(c))};l.Ma=function(a){return this.Aa(a,!0)};
l.Ba=function(a){var b=a.id;a={id:b,width:a.width,height:a.height,left:a.left,top:a.top,scale:this.Z,border:8,qa:ba,Y:0,na:0,ya:"maximized"==a.state,ha:"minimized"==a.state,C:"fullscreen"==a.state,oa:0,pa:0,s:0,ready:!t,U:null,D:null};this.b[b]=a;browser.tabs.query({windowId:b,active:!0},this.I);browser.tabs.query({windowId:b,url:G[0]},this.V);browser.tabs.query({windowId:b,url:G[1]},this.V);return a};l.Ca=function(a){M(this,5,1,32,[a]);delete this.b[a]};
l.Ya=function(a){if(0<a){var b=this.b[a];b&&(b.U||Va(this,b,!0),r&&this.ra(a,!1,!0,500))}};l.Ua=function(a,b,c){var d=c.windowId,e=this.b[d];e&&(e.U||Va(this,e),e.s||this.I(c));"complete"==b.status&&(a=this.a[a])&&!a.h&&(a.h=!0,this.X(d))};l.Sa=function(a){this.P=0;this.h&&this.K(4294967295);var b=a.windowId;a=a.tabId;var c=this.a[a];c&&!c.windowId&&(c.windowId=b);if(c=this.b[b])T(this,c.s),c.s=a,browser.tabs.get(a,this.I),this.X(b)};
l.Ta=function(a,b){var c=b.newWindowId,d=this.u,e;for(e in d)(port=d[e])&&port.tabId==a&&(port.windowId=c);T(this,a,!0)};function Xa(a,b,c,d,e){a.h&&a.K(4294967295);var f=a.b[b];f&&f.s==c&&(d&&(f.pa=d),e&&(f.oa=e),T(a,c),a.ra(b,d||e,!1,250))}function Za(a,b){var c=a.f[b];if(c){var d=c.j;c.j=c.m=null;c.A&&W(a,c);d&&d.abort()}}l.Qa=function(a,b){if(4==a.readyState){var c=[b,0],d={};200==a.status&&(d[115]=a.response);M(this,16,1,48,c,d);Za(this,b)}};
function $a(a,b){var c=a.v||b.a&128;if(c&&b.h)return b.v=3,b.b|=2052,3;var d=a.c,e=new URL(b.url),f=ab(e.pathname);return f&&!e.search&&b.u&&d[2].test(f)?1:!c||!t||b.i||b.c||e.search||d[9].test(e.hostname)||!d[1].test(f)?4:(b.v=1,b.b|=8,5)}
function bb(a,b){if(b.R)return Z(a,b,6),1;var c=b.h,d=b.statusCode;if(!c&&200!=d&&206!=d)return 1;var e=a.c,f=b.url,d=b.c,h=Y(b.responseHeaders,"Content-Type"),g=Y(b.responseHeaders,"Content-Disposition"),k=cb(h).toLowerCase(),m="attachment"==cb(g).toLowerCase();if(b.u&&!m&&"text/html"==k&&!c){if(b.g){if(c=a.i[[b.tabId,b.frameId]])c.c=!0;Z(a,b,5)}return 1}if(b.i||!d&&!e[-9])return 1;var n=c,q=!1,B=!1,D=!1,v=!1,Ja=!1,f=new URL(f),K=f.hostname,F=f.pathname,g=(h=db(g,"filename")||db(h,"name"))&&ab(h),
A=!1,X=!1;if(h)if(g||c)A=X=!0,b.J=h;else if(!d)return 1;X||(h=F.split("/").pop(),(g=ab(h))&&g.toLowerCase()==k.split("/").pop()&&(A=!0));if(!A){var N=va[k];if(N)if(N=N.split("|"),g&&0<=N.indexOf(g))A=!0;else if(d||!g)g=N.shift(),A=!0;!g||A||!m&&k&&!e[10].test(k)||(A=!0)}if(!c){if(d&&oa.test(K))if("/videoplayback"==F)q=A=!0;else if(F.startsWith("/api/timedtext")&&"text/xml"==k)B=!0;else if(F.endsWith("/watch")&&0<parseInt(f.searchParams.get("pbj"))&&"application/json"==k)Ja=!0;else{if(F.endsWith("/get_video_info")&&
"application/x-www-form-urlencoded"==k||F.endsWith("/api_video_info")&&"application/x-www-form-urlencoded"==k||F.startsWith("/api/manifest/dash")&&"video/vnd.mpeg.dash.mpd"==k)D=!0}else d&&pa.test(K)?("M4S"==g&&(A=!0),"player.vimeo.com"==K&&F.startsWith("/video/")&&"application/json"==k&&(D=!0)):d&&qa.test(K)&&(K=ra.exec(F))&&"application/x-javascript"==k&&((k=sa.exec(b.port.url))&&K[1]!=k[1]||(D=!0));d&&A&&("M3U8"==g||"F4M"==g?D=!0:"F4F"==g&&(h.endsWith("Seg1-Frag1")||h.endsWith("Seg1-Frag2")||h.includes("Seg1-Frag2_"))&&
(v=!0));A&&(d&&e[3].test(g)?q=!0:!b.i&&e[1].test(g)&&(n=d?!e[-4]&&!e[4].test(g):!0))}n&&!c&&(k=e[9])&&k.test(f.hostname)&&(n=!1);if(q){var O;if(k=e[11])if(k.test(f.hostname))q=!1;else if(e=b.frameId?a.a[b.tabId]:b.port)if(O=new URL(e.url),k.test(O.hostname))q=!1}D||v?(O=new XMLHttpRequest,O.responseType=v?"blob":"text",b.j=O,B=!0):Ja&&(B=b.m=!0);if(!n&&!q&&!B)return 1;A&&(b.O=g);X&&(b.J=h);b.g|=B;b.v=n?2:q?4:5;b.b|=c?2052:q||B?256:(d?4096:0)|(X||m?0:8388608)|16;return n?3:q?2:4}
function Z(a,b,c){var d,e=b.a,f=b.requestHeaders;if(1==(e&31)&&null==f)R(b.url,La(a,b,c,d,!0));else{null==c&&(c=b.v);null==d&&(d=0);var h=b.id,g=b.port&&b.port.id,k=b.timeStamp,m=b.responseHeaders,n=b.M,q=b.b;e&64&&(q|=2097152);"POST"==b.method&&(q|=512);t&&4>c&&(d|=1);b.g&&b.j&&(d|=1);b.g&&5!=c&&(d|=16);b.c&&(d|=16);c=[h,g,Math.floor(k/1E3),Math.floor(k%1E3*1E3),e&31,c];e={};e[6]=Ma(b.url);e[17]=b.G;e[4]=b.O;e[100]=b.J;e[8]=q;e[11]=eb(f);e[13]=eb(m);e[18]=eb(n);b.f&&(e[14]=Ya(b.f,Y(f,"Content-Type")));
b.B&&(e[19]=Ya(b.B,Y(n,"Content-Type")));null==f&&(e[50]=b.port&&b.port.url,e[51]=void 0,e[54]=navigator.userAgent);if(b=a.a[b.tabId])e[7]=b.url,e[110]=b.title;M(a,13,1,d,c,e)}}
function W(a,b,c,d){var e=a.f,f,h;"object"==typeof b?f=b.requestId:(f=b,b=e[f]);if(d)if(0>b.tabId)h={cancel:!0};else if(p&&c&&587202560>w)h=[{name:"Connection",value:"close"},{name:"Content-Type",value:"multipart/related"},{name:"Content-Length",value:"0"}],h={responseHeaders:h};else if(p||(t?c&&939524096>w:c)){h=a.M;if(r||!h){h=ia;var g=a.i[[b.tabId,b.frameId]];g&&!g.f&&(h+="?back=1")}h={redirectUrl:h}}else h={cancel:!0};if(b){c&&c.ip&&(b.b|=c.ip.includes(":")?4194304:0);(c=b.resolve)&&void 0!==
d&&(b.resolve=b.reject=null,c(h||{}));if(d=b.reject)b.resolve=b.reject=null,d();!b.v||b.A||c||d||Z(a,b);if(b.j||b.m)return b.A=!0,h;delete e[f];r&&delete e[b.id];b.c&&(e[b.id]={url:b.url,port:b.port})}return h}l.Va=function(a){var b=a.url,c=new URL(b);if(c.search.startsWith("?d="))return a=this.a[a.tabId],this.W("idmreg:"+b.substr(c.protocol.length),null,a&&a.url),{redirectUrl:ia+"?register=1"}};
l.ka=function(a){if(!(t&&0>C.indexOf(a.type))){var b=a.tabId,c=a.frameId;if(!(0>b||0>c)){var d=a.requestId,e=a.url,f=Na(e),h=a.type.endsWith("_frame"),g="POST"==a.method;if(h){var k=Ha(this,b,c,a.parentFrameId);k.a!=d&&(k.a=d,k.G=e,k.url=null,k.c=!1);k.f=g}if(this.v||f&128){var e=this.O,k=this.$,m=!0;if(!k&&g&&a.requestBody){var g=a.requestBody,n=g.raw;if(n)for(var q=0;q<n.length&&(n[q].bytes||(n=null));q++);n||g.formData||p&&g.error?(d=this.f[d])?d.requestBody=g:Ga(this,a):m=!1}if(e&&m)switch(a.a=
f,a.f=a.requestBody,a.u=h,a.c=0<=E.indexOf(a.type),a.h=e,a.i=k,a.port=this.a[[b,c]],$a(this,a)){case 5:if(t)return new Promise(this.Ga.bind(this,a));case 3:return W(this,a,null,!0)}}}}};
l.la=function(a){if(!(t&&0>C.indexOf(a.type))){var b=a.tabId;if(0<b){var c=a.requestId,d=a.url,e=a.method,f=Na(d);if(!f||"GET"!=e&&"POST"!=e)return W(this,a);a.h=this.O;a.i=this.$;if(c=this.f[c])a.id=c.id,a.port=c.port,a.f=c.requestBody,c.a&&(a.G=c.G||c.url,a.M=c.M||c.requestHeaders,a.B=c.B||c.f,a.h=c.h,a.i=c.i),!t||302!=c.statusCode&&303!=c.statusCode||(a.method=e="GET");var c=a.type,h=c.endsWith("_frame");if(!a.port&&!(a.port=this.a[[b,a.frameId]])&&!h||"POST"==e&&(!a.f||a.f.error&&0<Y(a.requestHeaders,
"Content-Length")))return W(this,a);d.includes("#")&&(a.url=Ma(d));a.a=f;a.u=h;a.c=0<b&&0<=E.indexOf(c);a.g=na.test(d);switch($a(this,a)){case 5:if(t)return new Promise(this.Ga.bind(this,a));if(!a.h)break;case 3:return W(this,a,null,!0);case 1:return W(this,a)}Ga(this,a)}else if("xmlhttprequest"==a.type&&(a.P?a.P==ja:a.S?a.S==ka:1)){a=a.requestHeaders;b={};d=!1;for(e=0;e<a.length;e++)f=a[e],c=f.name.toLowerCase(),c.startsWith("x-idm-")?b[c.substr(6)]=d=!0:"origin"==c&&f.value==ja&&(b[c]=d=!0);if(d){for(e=
0;e<a.length;e++)f=a[e],c=f.name.toLowerCase(),b[c]?a.splice(e--,1):c.startsWith("x-idm-")&&(f.name=f.name.substr(6));return{requestHeaders:a}}}return null}};l.Ga=function(a,b,c){a.resolve=b;a.reject=c;Ga(this,a);Z(this,a)};
l.ma=function(a){if(!(t&&0>C.indexOf(a.type))){var b=this.f[a.requestId];if(b){var c=a.responseHeaders;if("image"==b.type){var d=Y(c,"Content-Type");if(d&&d.toLowerCase().startsWith("image/"))return W(this,b)}"quic"==Y(c,"Client-Protocol")?b.a|=64:(d=Y(c,"Alternate-Protocol"))&&d.endsWith(":quic,p=0")&&"chunked"!=Y(c,"Transfer-Encoding")&&(b.a|=64);if(this.v||b.a&192){var d=a.statusLine,e=parseInt(d.split(" ",2).pop());b.statusLine=d;b.statusCode=e;b.R=0<=fa.indexOf(e);b.responseHeaders=c;switch(bb(this,
b)){case 3:return W(this,b,a,!0)}}if(b.m)return{responseHeaders:c.concat({name:"X-IDM-Request-ID",value:b.id})}}}};l.Xa=function(a){if(!(t&&0>C.indexOf(a.type))){var b=this.f[a.requestId];if(b){if(b.u){var c=this.i[[b.tabId,b.frameId]];c&&(c.url=b.url)}W(this,b,a)}}};l.Wa=function(a){t&&0>C.indexOf(a.type)||W(this,a.requestId)};
l.da=function(a,b,c,d,e,f){if(void 0===a&&(this.ba=!1,a=new P(this,!0),browser.storage.local.get("version",Q(a,1)),(r?1073741824<=w:p)&&browser.extension.isAllowedIncognitoAccess(Q(a,2)),p&&(browser.management.get("jeaohhlajejodfjadcponpnjgkiikocn",Q(a,3)),browser.management.get("afmdpmddiokpdknaeofdnlclbpgehhce",Q(a,4))),u&&"ngpampappnmepgilojfohadhhmbhlaek"!=browser.runtime.id&&browser.management.get("ngpampappnmepgilojfohadhhmbhlaek",Q(a,5)),a.c()))return;a=browser.runtime.getManifest();a=a.version||
"";"object"==typeof b&&(b=b.version||"");c=null!=c&&!c;"object"==typeof d&&(d=d.enabled&&d.id);d&&browser.management.setEnabled(d,!1);"object"==typeof e&&(e=e.enabled&&e.id);e&&browser.management.setEnabled(e,!1);"object"==typeof f&&(f=f.enabled&&f.id);f&&browser.management.setEnabled(f,!1);a&&a!=b&&null!=b&&(browser.storage.local.set({version:a}),d=this.aa,f=d<(r?"v6.26b14":t?"v6.28":0),!b||!d||f||e)&&(a="current="+escape(a),b&&(a+="&previous="+escape(b)),c&&(a+="&incognito=1"),e&&(a+="&mulsrch=1"),
d&&(a+="&manager="+escape(d)),f&&(a+="&update=1"),r&&(a+="&msedge=1"),t&&(a+="&mzffox=1"),u&&(a+="&opera=1"),browser.tabs.create({url:browser.runtime.getURL("welcome.html?"+a)}))};function Wa(a,b){var c=browser.i18n.getMessage(b);t?browser.tabs.executeScript(a,{code:'window.alert(unescape("'+escape(c)+'"))'}):window.alert(c)}l.o=function(a,b){var c=Array.prototype.slice.call(arguments);if(t||r){var d=c[2];c[2]=function(){return d.apply(null,arguments)}}this.ua.push(c);b.addListener.apply(b,c.slice(2))};
function P(a){this.caller=arguments.callee.caller;this.f=a;this.b=Array.prototype.slice.call(arguments,1);this.a=0}function Q(a,b){a.a++;return a.h.bind(a,b)}P.prototype.c=function(){return this.a?(arguments.length&&(this.b=Array.prototype.slice.call(arguments)),!0):!1};P.prototype.h=function(a,b){browser.runtime.lastError;this.b[a]=b;0==--this.a&&this.caller.apply(this.f,this.b)};
P.prototype.g=function(a,b,c){var d=Array.prototype.slice.call(arguments,3);c&&(d=c.concat(d));a.apply(b,d);this&&0==--this.a&&this.caller.apply(this.f,this.b)};function La(a){var b=Array.prototype.slice.call(arguments,1),c=b[b.length-1];c instanceof P?c.a++:c=null;return P.prototype.g.bind(c,arguments.callee.caller,a,b)}function Ea(a){return browser.i18n.getMessage(a)||a}function Ma(a){var b=a.lastIndexOf("#");return 0>b||b<a.indexOf("?")?a:a.substr(0,b)}
function Oa(a){var b="";if(a&&a.length)for(var c=0;c<a.length;c++)b&&(b+="; "),b+=a[c].name,b+="=",b+=a[c].value;return b}function eb(a){if(!a||!a.length)return null;for(var b="",c=0;c<a.length;c++)b+=a[c].name,b+=": ",b+=a[c].value,b+="\n";return b}function Y(a,b){if(!a)return null;b=b.toLowerCase();for(var c=0;c<a.length;c++)if(a[c].name.toLowerCase()==b)return a[c].value;return null}
function db(a,b){if(!a)return null;var c,d,e=a.split(";");for(b=b.toLowerCase();e.length;){var f=e.shift(),h=f.indexOf("=");if(0<h){var g=f.substr(0,h).trim().toLowerCase(),k="*"==g[g.length-1];if(k)g=g.substr(0,g.length-1).trimRight();else if(d)continue;if(g==b)if(f=f.substr(h+1).trim(),h=f.length-1,'"'==f[0]&&'"'==f[h]&&(f=f.substring(1,h)),k){if(f=f.split("'",3),k=f.shift().toLowerCase(),(h="utf-8"==k||"utf8"==k)||!d)if(c=unescape(f.pop()),d=k,h)break}else c=unescape(f)}else 0>h&&null==c&&f.trim().toLowerCase()==
b&&(c="")}return c}function cb(a){return a&&(a=a.split(";",1).shift().trim())&&0>a.indexOf("=")&&unescape(a)||""}
function Ya(a,b){if(!a)return null;var c=a.raw;if(c){for(var d=String.fromCharCode,e="",f=0;f<c.length;f++){var h=c[f].bytes;if(!h)return null;for(var h=new Uint8Array(h),g=h.length,k=0;k<g;k++)e+=d(h[k])}return e}c=a.formData;if(!c)return null;f=cb(b).toLowerCase();e=[];if(f&&"application/x-www-form-urlencoded"!=f)if("multipart/form-data"==f){(h=db(b,"boundary"))||(h="----WebKitFormBoundary"+Math.random().toString(36).substr(2));for(d in c)for(g=c[d],f=0;f<g.length;f++)e.push("--",h,'\r\nContent-Disposition: form-data; name="',
d,'"\r\n\r\n',g[f],"\r\n");e.push("--",h,"--\r\n")}else return null;else for(d in c)for(g=c[d],d=d.split(" ").map(encodeURIComponent).join("+"),f=0;f<g.length;f++)e.length&&e.push("&"),e.push(d,"=",g[f].split(" ").map(encodeURIComponent).join("+"));return e.join("")}function ab(a){return(a=ha.exec(a))?a.pop().toUpperCase():""}function Na(a,b){var c=a.split("://",1).shift().toLowerCase(),c=ua[c]||0;return b?c&31:c}
function fb(a){if(void 0===a){var b=navigator.userAgent;a=b.match(/\b(?!(?:Safari|Chrome|Gecko)\/)\w+\/(\d+)(?:.(\d+))?(?:.(\d+))?(?:.(\d+))?\b(?!.*[()])/);if(b=t?a:b.match(/\bChrome\/(\d+)\.(\d+)\.(\d+)\.(\d+)\b/)){w=b[1]<<24|b[2]<<22|b[3]<<8|b[4];x=b[0];y=a?a[0]:b[0];browser.runtime.getBrowserInfo&&browser.runtime.getBrowserInfo(fb);try{t&&browser.privacy.websites.firstPartyIsolate.get({},fb)}catch(c){}browser.webRequest.ResourceType&&browser.webRequest.ResourceType.MEDIA&&C.push("media")&&E.push("media");
t&&C.push("object_subrequest")&&E.push("object_subrequest")}}else"version"in a?(b=a.version.split(/\D+/),w=b[0]<<24|b[1]<<22|b[2]<<8|b[3],x=y=a.name+"/"+a.version):"value"in a&&(aa=a.value)}var Da=[[!0,-11,"menu_download_link","link,image",J.prototype.fa],[!0,-11,"menu_download_link","page,frame",J.prototype.fa,G],[!0,-11,"menu_download_selected","selection",J.prototype.wa],[!0,-12,"menu_download_all","page,frame",J.prototype.wa],[p,-11,"menu_download_item","link",J.prototype.fa,["chrome://downloads/*"]]];
String.prototype.startsWith||(String.prototype.startsWith=function(a,b){return this.substr(b||0,a.length)===a});String.prototype.endsWith||(String.prototype.endsWith=function(a,b){b=(null==b||b>this.length?this.length:b)-a.length;return 0<=b&&this.lastIndexOf(a,b)==b});String.prototype.includes||(String.prototype.includes=function(a,b){return 0<=this.indexOf(a,b)});fb();new J;

